-- ============================================================
-- NEXUS Database Migration 004: Platform Configs
-- ============================================================
-- Seeds default platform configurations.
-- These can be customized via the Platform Manager.
-- ============================================================

INSERT OR IGNORE INTO platforms (
  id, name, slug, url, title_max_chars, description_max,
  tag_count, tag_max_chars, audience, tone, seo_style,
  description_style, cta_style, forbidden_words, rules_json, sort_order
) VALUES

-- E-COMMERCE PLATFORMS
('platform-etsy', 'Etsy', 'etsy', 'https://etsy.com',
 140, 5000,
 13, 20,
 'Creative buyers, gift shoppers, handmade enthusiasts',
 'Warm, personal, handmade feel',
 'Keyword-rich, searchable',
 'Storytelling, conversion-focused',
 'Shop now button',
 '["best seller", "unique design", "handmade with love", "one of a kind"]',
 '{"shopify_sync": true, "etsy_rank_signal": true}',
 1),

('platform-gumroad', 'Gumroad', 'gumroad', 'https://gumroad.com',
 80, 10000,
 0, 0,
 'Digital product buyers, creators, entrepreneurs',
 'Direct, value-focused',
 'Keyword-match',
 'Feature-led, benefit-focused',
 'Get it now',
 '[]',
 '{"instant_delivery": true, "gumroad_discover": true}',
 2),

('platform-shopify', 'Shopify', 'shopify', 'https://shopify.com',
 70, 160,
 0, 0,
 'Broad e-commerce audience',
 'Professional, brand-focused',
 'Google SEO optimized',
 'Brand story, trust signals',
 'Shop now',
 '[]',
 '{"seo_title": 70, "seo_description": 320}',
 3),

('platform-amazon', 'Amazon', 'amazon', 'https://amazon.com',
 200, 2000,
 5, 50,
 'Price-conscious, review-driven shoppers',
 'Informative, feature-rich',
 'Keyword-stuffed bullets',
 'A+ content, feature bullets',
 'Add to cart',
 '["best", "cheapest", "top rated"]',
 '{"buy_box": true, "prime_eligible": true}',
 4),

-- CRAFT & DESIGN PLATFORMS
('platform-creative-fabrica', 'Creative Fabrica', 'creative_fabrica', 'https://creativefabrica.com',
 60, 1000,
 0, 0,
 'Crafters, SVG users, DIY enthusiasts',
 'Crafty, tutorial-friendly',
 'Use-case keywords',
 'Project-focused, format listings',
 'Download now',
 '[]',
 '{"file_formats": ["SVG", "DXF", "PNG"], "commercial_license": true}',
 5),

('platform-design bundles', 'Design Bundles', 'design-bundles', 'https://designbundles.net',
 60, 800,
 0, 0,
 'Graphic designers, small business owners',
 'Professional, bundle-focused',
 'Style keywords',
 'List format, included items',
 'Add to cart',
 '[]',
 '{"bundle_discount": true}',
 6),

-- PRINT-ON-DEMAND
('platform-redbubble', 'Redbubble', 'redbubble', 'https://redbubble.com',
 100, 500,
 0, 0,
 'Art lovers, pop culture fans',
 'Creative, art-focused',
 'Style + subject keywords',
 'Artist statement style',
 'Add to cart',
 '[]',
 '{"tags": 20}',
 7),

('platform-zazzle', 'Zazzle', 'zazzle', 'https://zazzle.com',
 100, 1000,
 0, 0,
 'Gift shoppers, personalization seekers',
 'Fun, customizable',
 'Gift occasion keywords',
 'Personalization highlights',
 'Customize it',
 '[]',
 '{"customization": true}',
 8),

-- DIGITAL PRODUCT SPECIFIC
('platform-leetcode', 'LeetCode', 'leetcode', 'https://leetcode.com',
 50, 500,
 0, 0,
 'Software engineers, coding interview preppers',
 'Technical, efficiency-focused',
 'Topic keywords',
 'Problem-solution format',
 'Solve now',
 '[]',
 '{"difficulty": true, "solutions_count": true}',
 9),

('platform-gumroad-plus', 'Gumroad Plus', 'gumroad-plus', 'https://gumroad.com/plus',
 80, 10000,
 0, 0,
 'Established creators with audience',
 'Community-focused',
 'Member benefits',
 'Value proposition',
 'Join now',
 '[]',
 '{"membership": true, "discord_access": true}',
 10);
