-- ============================================================
-- Migration 011: Real product deliverable (the actual file a buyer gets)
-- ============================================================
-- Until now a "product" was a marketing brief + tags + hero image. This adds
-- the real, downloadable deliverable the buyer pays for — generated by the
-- agent team, rendered to a PDF (via Browser Rendering) and stored in R2.
-- `deliverable_url`    serves the rendered PDF (/api/assets/r2/<key>).
-- `deliverable_format` is the recipe used (Planner, Checklist, Template, …).

ALTER TABLE products ADD COLUMN deliverable_url TEXT;
ALTER TABLE products ADD COLUMN deliverable_format TEXT;
